# Generated by Django 5.1.4 on 2025-02-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=55)),
                ('variant', models.CharField(max_length=55)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
